name: Validate & Publish Features
on:
    release:
        types:
            - published
    pull_request: &changes
        branches:
            - main
        paths:
            - src/**
            - .github/workflows/features.yml
    push: *changes

concurrency: features-${{github.ref}}

jobs:
    validate:
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        name: Validate Devcontainer Features
        runs-on: ubuntu-latest
        permissions:
            contents: read
        
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7

            - name: Validate Features
              uses: devcontainers/action@v1
              with:
                  validate-only: true
                  base-path-to-features: ./src

    publish:
        if: github.event_name == 'release'
        name: Publish Devcontainer Features
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v7

            - name: Inject Release Version
              run: |
                  version="${GITHUB_REF_NAME#v}"
                  for feature in src/*/devcontainer-feature.json; do
                      jq --arg version "$version" '.version = $version' "$feature" > "$feature.tmp"
                      mv "$feature.tmp" "$feature"
                  done

            - name: Publish Features
              uses: devcontainers/action@v1
              with:
                  publish-features: true
                  base-path-to-features: ./src
                  features-namespace: samyarsadat/devcontainers/features
                  disable-repo-tagging: true
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
